// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
// On Fri Apr 4 18:23:34 IST 2025
`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkcsr(
    input CLK,
    input RST_N,

    // Inputs
    input [11:0] system_instruction_csr_address,
    input [31:0] system_instruction_op1,
    input [2:0] system_instruction_funct3,
    input [1:0] system_instruction_lpc,
    input EN_system_instruction,
    input [5:0] take_trap_type_cause,
    input [31:0] take_trap_pc,
    input [31:0] take_trap_badaddr,
    input clint_msip_intrpt,
    input clint_mtip_intrpt,
    // input [63:0] clint_mtime_c_mtime, // Removed mtime input
    input ext_interrupt_ex_i,
    input EN_clint_msip,
    input EN_clint_mtip,
    // input EN_clint_mtime, // Removed mtime enable
    // input EN_incr_minstret, // Removed minstret enable
    input EN_ext_interrupt,
    input EN_take_trap,

    // Outputs
    output [64:0] system_instruction,
    output RDY_system_instruction,
    // output [83:0] mv_csr_decode, // Removed mv_csr_decode output
    // output RDY_mv_csr_decode,
    output [31:0] take_trap,
    output RDY_take_trap,
    output RDY_clint_msip,
    output RDY_clint_mtip,
    // output RDY_clint_mtime, // Removed mtime ready
    // output RDY_incr_minstret, // Removed minstret ready
    output RDY_ext_interrupt,
    output mv_csr_misa_c,
    output RDY_mv_csr_misa_c,
    output mv_interrupt,
    // output [1:0] mv_curr_priv, // Removed privilege level output
    // output RDY_mv_curr_priv,
    output [31:0] csr_mstatus,
    output RDY_csr_mstatus
);

  // Simplified assignment for system_instruction and take_trap
  assign system_instruction =
    (system_instruction_funct3 == 3'd0 &&
    (system_instruction_csr_address[11:8] == 4'h0 || system_instruction_csr_address[11:8] == 4'h3)) ?
    {system_instruction_op1, 32'd0} :
    {32'd0, system_instruction_op1};

  assign RDY_system_instruction = 1'b1;
  // assign mv_csr_decode = csrfile_mv_csr_decode;
  // assign RDY_mv_csr_decode = 1'b1;

  // Directly assign values for other outputs
  assign take_trap = csrfile_upd_on_trap;
  assign RDY_take_trap = 1'b1;

  assign RDY_clint_msip = 1'b1;
  assign RDY_clint_mtip = 1'b1;
  // assign RDY_clint_mtime = 1'b1;
  // assign RDY_incr_minstret = 1'b1;
  assign RDY_ext_interrupt = 1'b1;

  assign mv_csr_misa_c = csrfile_mv_csr_misa_c;
  assign RDY_mv_csr_misa_c = 1'b1;
  assign mv_interrupt = csrfile_mv_interrupt;
  // assign mv_curr_priv = csrfile_mv_curr_priv;
  // assign RDY_mv_curr_priv = 1'b1;

  assign csr_mstatus = csrfile_csr_mstatus;
  assign RDY_csr_mstatus = 1'b1;

  // Submodule csrfile instantiation with reduced ports
  mkcsrfile csrfile(
    .CLK(CLK),
    .RST_N(RST_N),
    .clint_msip_intrpt(clint_msip_intrpt),
    // .clint_mtime_c_mtime(clint_mtime_c_mtime),
    .clint_mtip_intrpt(clint_mtip_intrpt),
    .ext_interrupt_ex_i(ext_interrupt_ex_i),
    .read_csr_addr(system_instruction_csr_address),
    .upd_on_trap_cause(take_trap_type_cause),
    .upd_on_trap_pc(take_trap_pc),
    .upd_on_trap_tval(take_trap_badaddr),
    .write_csr_addr(system_instruction_csr_address),
    .write_csr_lpc(system_instruction_lpc),
    .write_csr_word(system_instruction_op1 | csrfile_read_csr),
    .EN_read_csr(EN_system_instruction),
    .EN_write_csr(EN_system_instruction && system_instruction_funct3 != 3'd0),
    .EN_upd_on_ret(EN_system_instruction && system_instruction_funct3 == 3'd0 && (system_instruction_csr_address[11:8] == 4'h0 || system_instruction_csr_address[11:8] == 4'h3)),
    .EN_upd_on_trap(EN_take_trap),
    // .EN_incr_minstret(EN_incr_minstret),
    .EN_clint_msip(EN_clint_msip),
    .EN_clint_mtip(EN_clint_mtip),
    // .EN_clint_mtime(EN_clint_mtime),
    .EN_ext_interrupt(EN_ext_interrupt),
    .read_csr(csrfile_read_csr),
    .RDY_read_csr(),
    .RDY_write_csr(),
    .upd_on_ret(csrfile_upd_on_ret),
    .RDY_upd_on_ret(),
    .upd_on_trap(csrfile_upd_on_trap),
    .RDY_upd_on_trap(),
    // .RDY_incr_minstret(),
    // .mv_csr_decode(csrfile_mv_csr_decode),
    // .RDY_mv_csr_decode(),
    .mv_csr_misa_c(csrfile_mv_csr_misa_c),
    .RDY_mv_csr_misa_c(),
    // .mv_curr_priv(csrfile_mv_curr_priv),
    // .RDY_mv_curr_priv(),
    .csr_mstatus(csrfile_csr_mstatus),
    .RDY_csr_mstatus(),
    .RDY_clint_msip(),
    .RDY_clint_mtip(),
    // .RDY_clint_mtime(),
    .RDY_ext_interrupt(),
    .mv_interrupt(csrfile_mv_interrupt)
  );

endmodule  // mkcsr