//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Mar 31 00:26:12 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// rx_stage3_common_deq_ena       O     1
// rx_stage3_type_deq_ena         O     1
// rx_stage3_dump_deq_ena         O     1
// RDY_memory_response_put        O     1 const
// commit_rd_get                  O    37
// RDY_commit_rd_get              O     1
// operand_fwding_get             O    38
// RDY_operand_fwding_get         O     1 const
// flush_fst                      O    32
// RDY_flush_fst                  O     1 const
// flush_snd                      O     1
// RDY_flush_snd                  O     1 const
// mv_csr_decode                  O   120
// RDY_mv_csr_decode              O     1 const
// mv_csr_misa_c                  O     1 reg
// RDY_mv_csr_misa_c              O     1 const
// RDY_clint_msip                 O     1 const
// RDY_clint_mtip                 O     1 const
// RDY_clint_mtime                O     1 const
// RDY_ext_interrupt              O     1 const
// csr_updated                    O     1 const
// RDY_csr_updated                O     1 const
// mv_interrupt                   O     1
// dump_get                       O   103 reg
// RDY_dump_get                   O     1 reg
// mv_trigger_data1               O    40 reg
// RDY_mv_trigger_data1           O     1 const
// mv_trigger_data2               O    64 reg
// RDY_mv_trigger_data2           O     1 const
// mv_trigger_enable              O     2
// RDY_mv_trigger_enable          O     1 const
// mv_curr_priv                   O     2 reg
// RDY_mv_curr_priv               O     1 const
// RDY_ma_delayed_output          O     1 const
// RDY_ma_events                  O     1 const
// mv_event_exceptions            O     1
// RDY_mv_event_exceptions        O     1 const
// mv_event_interrupts            O     1
// RDY_mv_event_interrupts        O     1 const
// counter_values_fst             O    32 reg
// RDY_counter_values_fst         O     1 const
// counter_values_snd             O    64 reg
// RDY_counter_values_snd         O     1 const
// mv_pmp_cfg                     O    32 reg
// RDY_mv_pmp_cfg                 O     1 const
// mv_pmp_addr                    O   120 reg
// RDY_mv_pmp_addr                O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// rx_stage3_common_notEmpty_b    I     1 unused
// rx_stage3_common_first_deq_rdy_b  I     1
// rx_stage3_common_first_x       I    38
// rx_stage3_type_notEmpty_b      I     1 unused
// rx_stage3_type_first_deq_rdy_b  I     1
// rx_stage3_type_first_x         I    51
// rx_stage3_dump_notEmpty_b      I     1 unused
// rx_stage3_dump_first_deq_rdy_b  I     1
// rx_stage3_dump_first_x         I    64
// memory_response_put            I    34
// clint_msip_intrpt              I     1 reg
// clint_mtip_intrpt              I     1 reg
// clint_mtime_c_mtime            I    64 reg
// ext_interrupt_i                I     1 reg
// ma_delayed_output_r            I    33
// ma_events_e                    I    11
// EN_memory_response_put         I     1
// EN_clint_msip                  I     1
// EN_clint_mtip                  I     1
// EN_clint_mtime                 I     1
// EN_ext_interrupt               I     1
// EN_ma_delayed_output           I     1
// EN_ma_events                   I     1
// EN_commit_rd_get               I     1 unused
// EN_operand_fwding_get          I     1 unused
// EN_dump_get                    I     1
//
// Combinational paths from inputs to outputs:
//   (rx_stage3_common_first_deq_rdy_b,
//    rx_stage3_common_first_x,
//    rx_stage3_type_first_deq_rdy_b,
//    rx_stage3_type_first_x,
//    rx_stage3_dump_first_deq_rdy_b,
//    ma_delayed_output_r,
//    EN_ma_delayed_output,
//    EN_dump_get) -> rx_stage3_common_deq_ena
//   (rx_stage3_common_first_deq_rdy_b,
//    rx_stage3_common_first_x,
//    rx_stage3_type_first_deq_rdy_b,
//    rx_stage3_type_first_x,
//    rx_stage3_dump_first_deq_rdy_b,
//    ma_delayed_output_r,
//    EN_ma_delayed_output,
//    EN_dump_get) -> rx_stage3_type_deq_ena
//   (rx_stage3_common_first_deq_rdy_b,
//    rx_stage3_common_first_x,
//    rx_stage3_type_first_deq_rdy_b,
//    rx_stage3_type_first_x,
//    rx_stage3_dump_first_deq_rdy_b,
//    ma_delayed_output_r,
//    EN_ma_delayed_output,
//    EN_dump_get) -> rx_stage3_dump_deq_ena
//   (rx_stage3_common_first_deq_rdy_b,
//    rx_stage3_common_first_x,
//    rx_stage3_type_first_deq_rdy_b,
//    rx_stage3_type_first_x,
//    rx_stage3_dump_first_deq_rdy_b,
//    ma_delayed_output_r,
//    EN_ma_delayed_output,
//    EN_dump_get) -> RDY_commit_rd_get
//   (rx_stage3_common_first_deq_rdy_b,
//    rx_stage3_common_first_x,
//    rx_stage3_type_first_deq_rdy_b,
//    rx_stage3_type_first_x,
//    rx_stage3_dump_first_deq_rdy_b,
//    EN_ma_delayed_output,
//    EN_dump_get) -> flush_fst
//   (rx_stage3_common_first_deq_rdy_b,
//    rx_stage3_common_first_x,
//    rx_stage3_type_first_deq_rdy_b,
//    rx_stage3_type_first_x,
//    rx_stage3_dump_first_deq_rdy_b,
//    EN_ma_delayed_output,
//    EN_dump_get) -> flush_snd
//   (rx_stage3_common_first_deq_rdy_b,
//    rx_stage3_common_first_x,
//    rx_stage3_type_first_deq_rdy_b,
//    rx_stage3_type_first_x,
//    rx_stage3_dump_first_deq_rdy_b,
//    EN_ma_delayed_output,
//    EN_dump_get) -> mv_event_exceptions
//   (rx_stage3_common_first_deq_rdy_b,
//    rx_stage3_common_first_x,
//    rx_stage3_type_first_deq_rdy_b,
//    rx_stage3_type_first_x,
//    rx_stage3_dump_first_deq_rdy_b,
//    EN_ma_delayed_output,
//    EN_dump_get) -> mv_event_interrupts
//   (rx_stage3_common_first_deq_rdy_b,
//    rx_stage3_common_first_x,
//    rx_stage3_type_first_deq_rdy_b,
//    rx_stage3_type_first_x,
//    rx_stage3_dump_first_deq_rdy_b,
//    ma_delayed_output_r,
//    EN_ma_delayed_output,
//    EN_dump_get) -> commit_rd_get
//   (rx_stage3_common_first_deq_rdy_b,
//    rx_stage3_common_first_x,
//    rx_stage3_type_first_deq_rdy_b,
//    rx_stage3_type_first_x,
//    rx_stage3_dump_first_deq_rdy_b,
//    ma_delayed_output_r,
//    EN_ma_delayed_output,
//    EN_dump_get) -> operand_fwding_get
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkstage3(CLK,
		RST_N,

		rx_stage3_common_notEmpty_b,

		rx_stage3_common_first_deq_rdy_b,

		rx_stage3_common_first_x,

		rx_stage3_common_deq_ena,

		rx_stage3_type_notEmpty_b,

		rx_stage3_type_first_deq_rdy_b,

		rx_stage3_type_first_x,

		rx_stage3_type_deq_ena,

		rx_stage3_dump_notEmpty_b,

		rx_stage3_dump_first_deq_rdy_b,

		rx_stage3_dump_first_x,

		rx_stage3_dump_deq_ena,

		memory_response_put,
		EN_memory_response_put,
		RDY_memory_response_put,

		EN_commit_rd_get,
		commit_rd_get,
		RDY_commit_rd_get,

		EN_operand_fwding_get,
		operand_fwding_get,
		RDY_operand_fwding_get,

		flush_fst,
		RDY_flush_fst,

		flush_snd,
		RDY_flush_snd,

		mv_csr_decode,
		RDY_mv_csr_decode,

		mv_csr_misa_c,
		RDY_mv_csr_misa_c,

		clint_msip_intrpt,
		EN_clint_msip,
		RDY_clint_msip,

		clint_mtip_intrpt,
		EN_clint_mtip,
		RDY_clint_mtip,

		clint_mtime_c_mtime,
		EN_clint_mtime,
		RDY_clint_mtime,

		ext_interrupt_i,
		EN_ext_interrupt,
		RDY_ext_interrupt,

		csr_updated,
		RDY_csr_updated,

		mv_interrupt,

		EN_dump_get,
		dump_get,
		RDY_dump_get,

		mv_trigger_data1,
		RDY_mv_trigger_data1,

		mv_trigger_data2,
		RDY_mv_trigger_data2,

		mv_trigger_enable,
		RDY_mv_trigger_enable,

		mv_curr_priv,
		RDY_mv_curr_priv,

		ma_delayed_output_r,
		EN_ma_delayed_output,
		RDY_ma_delayed_output,

		ma_events_e,
		EN_ma_events,
		RDY_ma_events,

		mv_event_exceptions,
		RDY_mv_event_exceptions,

		mv_event_interrupts,
		RDY_mv_event_interrupts,

		counter_values_fst,
		RDY_counter_values_fst,

		counter_values_snd,
		RDY_counter_values_snd,

		mv_pmp_cfg,
		RDY_mv_pmp_cfg,

		mv_pmp_addr,
		RDY_mv_pmp_addr);
  input  CLK;
  input  RST_N;

  // action method rx_stage3_common_notEmpty
  input  rx_stage3_common_notEmpty_b;

  // action method rx_stage3_common_first_deq_rdy
  input  rx_stage3_common_first_deq_rdy_b;

  // action method rx_stage3_common_first
  input  [37 : 0] rx_stage3_common_first_x;

  // value method rx_stage3_common_deq_ena
  output rx_stage3_common_deq_ena;

  // action method rx_stage3_type_notEmpty
  input  rx_stage3_type_notEmpty_b;

  // action method rx_stage3_type_first_deq_rdy
  input  rx_stage3_type_first_deq_rdy_b;

  // action method rx_stage3_type_first
  input  [50 : 0] rx_stage3_type_first_x;

  // value method rx_stage3_type_deq_ena
  output rx_stage3_type_deq_ena;

  // action method rx_stage3_dump_notEmpty
  input  rx_stage3_dump_notEmpty_b;

  // action method rx_stage3_dump_first_deq_rdy
  input  rx_stage3_dump_first_deq_rdy_b;

  // action method rx_stage3_dump_first
  input  [63 : 0] rx_stage3_dump_first_x;

  // value method rx_stage3_dump_deq_ena
  output rx_stage3_dump_deq_ena;

  // action method memory_response_put
  input  [33 : 0] memory_response_put;
  input  EN_memory_response_put;
  output RDY_memory_response_put;

  // actionvalue method commit_rd_get
  input  EN_commit_rd_get;
  output [36 : 0] commit_rd_get;
  output RDY_commit_rd_get;

  // actionvalue method operand_fwding_get
  input  EN_operand_fwding_get;
  output [37 : 0] operand_fwding_get;
  output RDY_operand_fwding_get;

  // value method flush_fst
  output [31 : 0] flush_fst;
  output RDY_flush_fst;

  // value method flush_snd
  output flush_snd;
  output RDY_flush_snd;

  // value method mv_csr_decode
  output [119 : 0] mv_csr_decode;
  output RDY_mv_csr_decode;

  // value method mv_csr_misa_c
  output mv_csr_misa_c;
  output RDY_mv_csr_misa_c;

  // action method clint_msip
  input  clint_msip_intrpt;
  input  EN_clint_msip;
  output RDY_clint_msip;

  // action method clint_mtip
  input  clint_mtip_intrpt;
  input  EN_clint_mtip;
  output RDY_clint_mtip;

  // action method clint_mtime
  input  [63 : 0] clint_mtime_c_mtime;
  input  EN_clint_mtime;
  output RDY_clint_mtime;

  // action method ext_interrupt
  input  ext_interrupt_i;
  input  EN_ext_interrupt;
  output RDY_ext_interrupt;

  // value method csr_updated
  output csr_updated;
  output RDY_csr_updated;

  // value method mv_interrupt
  output mv_interrupt;

  // actionvalue method dump_get
  input  EN_dump_get;
  output [102 : 0] dump_get;
  output RDY_dump_get;

  // value method mv_trigger_data1
  output [39 : 0] mv_trigger_data1;
  output RDY_mv_trigger_data1;

  // value method mv_trigger_data2
  output [63 : 0] mv_trigger_data2;
  output RDY_mv_trigger_data2;

  // value method mv_trigger_enable
  output [1 : 0] mv_trigger_enable;
  output RDY_mv_trigger_enable;

  // value method mv_curr_priv
  output [1 : 0] mv_curr_priv;
  output RDY_mv_curr_priv;

  // action method ma_delayed_output
  input  [32 : 0] ma_delayed_output_r;
  input  EN_ma_delayed_output;
  output RDY_ma_delayed_output;

  // action method ma_events
  input  [10 : 0] ma_events_e;
  input  EN_ma_events;
  output RDY_ma_events;

  // value method mv_event_exceptions
  output mv_event_exceptions;
  output RDY_mv_event_exceptions;

  // value method mv_event_interrupts
  output mv_event_interrupts;
  output RDY_mv_event_interrupts;

  // value method counter_values_fst
  output [31 : 0] counter_values_fst;
  output RDY_counter_values_fst;

  // value method counter_values_snd
  output [63 : 0] counter_values_snd;
  output RDY_counter_values_snd;

  // value method mv_pmp_cfg
  output [31 : 0] mv_pmp_cfg;
  output RDY_mv_pmp_cfg;

  // value method mv_pmp_addr
  output [119 : 0] mv_pmp_addr;
  output RDY_mv_pmp_addr;

  // signals for module outputs
  wire [119 : 0] mv_csr_decode, mv_pmp_addr;
  wire [102 : 0] dump_get;
  wire [63 : 0] counter_values_snd, mv_trigger_data2;
  wire [39 : 0] mv_trigger_data1;
  wire [37 : 0] operand_fwding_get;
  wire [36 : 0] commit_rd_get;
  wire [31 : 0] counter_values_fst, flush_fst, mv_pmp_cfg;
  wire [1 : 0] mv_curr_priv, mv_trigger_enable;
  wire RDY_clint_msip,
       RDY_clint_mtime,
       RDY_clint_mtip,
       RDY_commit_rd_get,
       RDY_counter_values_fst,
       RDY_counter_values_snd,
       RDY_csr_updated,
       RDY_dump_get,
       RDY_ext_interrupt,
       RDY_flush_fst,
       RDY_flush_snd,
       RDY_ma_delayed_output,
       RDY_ma_events,
       RDY_memory_response_put,
       RDY_mv_csr_decode,
       RDY_mv_csr_misa_c,
       RDY_mv_curr_priv,
       RDY_mv_event_exceptions,
       RDY_mv_event_interrupts,
       RDY_mv_pmp_addr,
       RDY_mv_pmp_cfg,
       RDY_mv_trigger_data1,
       RDY_mv_trigger_data2,
       RDY_mv_trigger_enable,
       RDY_operand_fwding_get,
       csr_updated,
       flush_snd,
       mv_csr_misa_c,
       mv_event_exceptions,
       mv_event_interrupts,
       mv_interrupt,
       rx_stage3_common_deq_ena,
       rx_stage3_dump_deq_ena,
       rx_stage3_type_deq_ena;

  // inlined wires
  wire [37 : 0] wr_commit_wget, wr_operand_fwding_wget;
  wire [34 : 0] wr_memory_response_1_wget;
  wire [32 : 0] wr_flush_wget;
  wire ff_stage3_common_w_ena_whas,
       ff_stage3_dump_w_ena_whas,
       ff_stage3_type_w_ena_whas,
       wr_commit_whas,
       wr_event_exceptions_whas,
       wr_flush_whas,
       wr_operand_fwding_whas;

  // register rg_epoch
  reg rg_epoch;
  wire rg_epoch_D_IN, rg_epoch_EN;

  // register rg_rerun
  reg rg_rerun;
  wire rg_rerun_D_IN, rg_rerun_EN;

  // register wr_memory_response
  reg [34 : 0] wr_memory_response;
  wire [34 : 0] wr_memory_response_D_IN;
  wire wr_memory_response_EN;

  // ports of submodule csr
  wire [119 : 0] csr_mv_csr_decode, csr_mv_pmp_addr;
  wire [64 : 0] csr_system_instruction;
  wire [63 : 0] csr_clint_mtime_c_mtime,
		csr_counter_values_snd,
		csr_mv_trigger_data2;
  wire [39 : 0] csr_mv_trigger_data1;
  wire [31 : 0] csr_counter_values_fst,
		csr_mv_pmp_cfg,
		csr_system_instruction_op1,
		csr_take_trap,
		csr_take_trap_badaddr,
		csr_take_trap_pc;
  wire [11 : 0] csr_system_instruction_csr_address;
  wire [10 : 0] csr_ma_events_e;
  wire [5 : 0] csr_take_trap_type_cause;
  wire [2 : 0] csr_system_instruction_funct3;
  wire [1 : 0] csr_mv_curr_priv,
	       csr_mv_trigger_enable,
	       csr_system_instruction_lpc;
  wire csr_EN_clint_msip,
       csr_EN_clint_mtime,
       csr_EN_clint_mtip,
       csr_EN_ext_interrupt,
       csr_EN_incr_minstret,
       csr_EN_ma_events,
       csr_EN_system_instruction,
       csr_EN_take_trap,
       csr_clint_msip_intrpt,
       csr_clint_mtip_intrpt,
       csr_ext_interrupt_ex_i,
       csr_mv_csr_misa_c,
       csr_mv_interrupt;

  // ports of submodule dump_ff
  wire [102 : 0] dump_ff_D_IN, dump_ff_D_OUT;
  wire dump_ff_CLR, dump_ff_DEQ, dump_ff_EMPTY_N, dump_ff_ENQ, dump_ff_FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_increment_instruction_counter,
       CAN_FIRE_RL_instruction_commit,
       CAN_FIRE_RL_wr_memory_response__dreg_update,
       CAN_FIRE_clint_msip,
       CAN_FIRE_clint_mtime,
       CAN_FIRE_clint_mtip,
       CAN_FIRE_commit_rd_get,
       CAN_FIRE_dump_get,
       CAN_FIRE_ext_interrupt,
       CAN_FIRE_ma_delayed_output,
       CAN_FIRE_ma_events,
       CAN_FIRE_memory_response_put,
       CAN_FIRE_operand_fwding_get,
       CAN_FIRE_rx_stage3_common_first,
       CAN_FIRE_rx_stage3_common_first_deq_rdy,
       CAN_FIRE_rx_stage3_common_notEmpty,
       CAN_FIRE_rx_stage3_dump_first,
       CAN_FIRE_rx_stage3_dump_first_deq_rdy,
       CAN_FIRE_rx_stage3_dump_notEmpty,
       CAN_FIRE_rx_stage3_type_first,
       CAN_FIRE_rx_stage3_type_first_deq_rdy,
       CAN_FIRE_rx_stage3_type_notEmpty,
       WILL_FIRE_RL_increment_instruction_counter,
       WILL_FIRE_RL_instruction_commit,
       WILL_FIRE_RL_wr_memory_response__dreg_update,
       WILL_FIRE_clint_msip,
       WILL_FIRE_clint_mtime,
       WILL_FIRE_clint_mtip,
       WILL_FIRE_commit_rd_get,
       WILL_FIRE_dump_get,
       WILL_FIRE_ext_interrupt,
       WILL_FIRE_ma_delayed_output,
       WILL_FIRE_ma_events,
       WILL_FIRE_memory_response_put,
       WILL_FIRE_operand_fwding_get,
       WILL_FIRE_rx_stage3_common_first,
       WILL_FIRE_rx_stage3_common_first_deq_rdy,
       WILL_FIRE_rx_stage3_common_notEmpty,
       WILL_FIRE_rx_stage3_dump_first,
       WILL_FIRE_rx_stage3_dump_first_deq_rdy,
       WILL_FIRE_rx_stage3_dump_notEmpty,
       WILL_FIRE_rx_stage3_type_first,
       WILL_FIRE_rx_stage3_type_first_deq_rdy,
       WILL_FIRE_rx_stage3_type_notEmpty;

  // declarations used by system tasks
  // synopsys translate_off
  reg TASK_testplusargs___d14;
  reg TASK_testplusargs___d15;
  reg TASK_testplusargs___d16;
  reg [63 : 0] v__h2104;
  reg TASK_testplusargs___d26;
  reg TASK_testplusargs___d27;
  reg TASK_testplusargs___d28;
  reg [63 : 0] v__h2314;
  reg TASK_testplusargs___d40;
  reg TASK_testplusargs___d41;
  reg TASK_testplusargs___d42;
  reg [63 : 0] v__h2544;
  reg TASK_testplusargs___d138;
  reg TASK_testplusargs___d139;
  reg TASK_testplusargs___d140;
  reg [63 : 0] v__h3959;
  reg TASK_testplusargs___d148;
  reg TASK_testplusargs___d149;
  reg TASK_testplusargs___d150;
  reg [63 : 0] v__h3622;
  reg TASK_testplusargs___d185;
  reg TASK_testplusargs___d186;
  reg TASK_testplusargs___d187;
  reg [63 : 0] v__h4447;
  reg TASK_testplusargs___d245;
  reg TASK_testplusargs___d246;
  reg TASK_testplusargs___d247;
  reg [63 : 0] v__h5691;
  reg TASK_testplusargs___d269;
  reg TASK_testplusargs___d270;
  reg TASK_testplusargs___d271;
  reg [63 : 0] v__h5765;
  reg TASK_testplusargs___d280;
  reg TASK_testplusargs___d281;
  reg TASK_testplusargs___d282;
  reg [63 : 0] v__h5860;
  reg rg_rerun_18_AND_TASK_testplusargs_38_OR_TASK_t_ETC___d143;
  reg ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d153;
  reg ff_stage3_type_w_data_wget__7_BIT_0_4_AND_NOT__ETC___d190;
  reg NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d192;
  reg wr_memory_response_10_BIT_1_15_AND_TASK_testpl_ETC___d250;
  reg NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d254;
  reg NOT_wr_memory_response_10_BIT_34_11_62_OR_NOT__ETC___d274;
  reg NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d277;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d86;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d89;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d91;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d98;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d102;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d105;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d108;
  reg TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d115;
  reg NOT_rg_epoch_20_EQ_IF_ff_stage3_common_w_data__ETC___d285;
  // synopsys translate_on

  // remaining internal signals
  wire [102 : 0] _dfoo2,
		 csr_mv_curr_priv__79_CONCAT_ff_stage3_dump_w_d_ETC___d232;
  wire [37 : 0] _dfoo10;
  wire [32 : 0] _dfoo14;
  wire [31 : 0] _theResult_____1_fst__h4142,
		_theResult____h4019,
		_theResult____h4904,
		_theResult____h5217,
		data__h4022,
		x__read_rdvalue__h6674;
  wire [5 : 0] rx_stage3_type_first_x_BITS_37_TO_32__q1, type_cause__h5287;
  wire [4 : 0] x__read_rdaddr__h6673;
  wire NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d175,
       NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d183,
       NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d198,
       _dfoo11,
       _dfoo15,
       _dfoo17,
       _dfoo25,
       ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d239,
       ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d266,
       rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121,
       rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d124,
       rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d147,
       rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d160,
       rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d196,
       rg_rerun_18_OR_ff_stage3_type_w_data_whas__6_A_ETC___d123,
       rg_rerun_18_OR_ff_stage3_type_w_data_whas__6_A_ETC___d134,
       wr_memory_response_10_BIT_0_12_EQ_rg_epoch_20___d213,
       x__h5568,
       x_wget__h1930;

  // action method rx_stage3_common_notEmpty
  assign CAN_FIRE_rx_stage3_common_notEmpty = 1'd1 ;
  assign WILL_FIRE_rx_stage3_common_notEmpty = 1'd1 ;

  // action method rx_stage3_common_first_deq_rdy
  assign CAN_FIRE_rx_stage3_common_first_deq_rdy = 1'd1 ;
  assign WILL_FIRE_rx_stage3_common_first_deq_rdy = 1'd1 ;

  // action method rx_stage3_common_first
  assign CAN_FIRE_rx_stage3_common_first = 1'd1 ;
  assign WILL_FIRE_rx_stage3_common_first = 1'd1 ;

  // value method rx_stage3_common_deq_ena
  assign rx_stage3_common_deq_ena = ff_stage3_common_w_ena_whas ;

  // action method rx_stage3_type_notEmpty
  assign CAN_FIRE_rx_stage3_type_notEmpty = 1'd1 ;
  assign WILL_FIRE_rx_stage3_type_notEmpty = 1'd1 ;

  // action method rx_stage3_type_first_deq_rdy
  assign CAN_FIRE_rx_stage3_type_first_deq_rdy = 1'd1 ;
  assign WILL_FIRE_rx_stage3_type_first_deq_rdy = 1'd1 ;

  // action method rx_stage3_type_first
  assign CAN_FIRE_rx_stage3_type_first = 1'd1 ;
  assign WILL_FIRE_rx_stage3_type_first = 1'd1 ;

  // value method rx_stage3_type_deq_ena
  assign rx_stage3_type_deq_ena = ff_stage3_type_w_ena_whas ;

  // action method rx_stage3_dump_notEmpty
  assign CAN_FIRE_rx_stage3_dump_notEmpty = 1'd1 ;
  assign WILL_FIRE_rx_stage3_dump_notEmpty = 1'd1 ;

  // action method rx_stage3_dump_first_deq_rdy
  assign CAN_FIRE_rx_stage3_dump_first_deq_rdy = 1'd1 ;
  assign WILL_FIRE_rx_stage3_dump_first_deq_rdy = 1'd1 ;

  // action method rx_stage3_dump_first
  assign CAN_FIRE_rx_stage3_dump_first = 1'd1 ;
  assign WILL_FIRE_rx_stage3_dump_first = 1'd1 ;

  // value method rx_stage3_dump_deq_ena
  assign rx_stage3_dump_deq_ena = ff_stage3_dump_w_ena_whas ;

  // action method memory_response_put
  assign RDY_memory_response_put = 1'd1 ;
  assign CAN_FIRE_memory_response_put = 1'd1 ;
  assign WILL_FIRE_memory_response_put = EN_memory_response_put ;

  // actionvalue method commit_rd_get
  assign commit_rd_get = wr_commit_wget[36:0] ;
  assign RDY_commit_rd_get = wr_commit_whas && wr_commit_wget[37] ;
  assign CAN_FIRE_commit_rd_get = RDY_commit_rd_get ;
  assign WILL_FIRE_commit_rd_get = EN_commit_rd_get ;

  // actionvalue method operand_fwding_get
  assign operand_fwding_get =
	     { x__read_rdaddr__h6673,
	       x__read_rdvalue__h6674,
	       wr_operand_fwding_whas && wr_operand_fwding_wget[0] } ;
  assign RDY_operand_fwding_get = 1'd1 ;
  assign CAN_FIRE_operand_fwding_get = 1'd1 ;
  assign WILL_FIRE_operand_fwding_get = EN_operand_fwding_get ;

  // value method flush_fst
  assign flush_fst = wr_flush_wget[32:1] ;
  assign RDY_flush_fst = 1'd1 ;

  // value method flush_snd
  assign flush_snd = wr_flush_whas && wr_flush_wget[0] ;
  assign RDY_flush_snd = 1'd1 ;

  // value method mv_csr_decode
  assign mv_csr_decode = csr_mv_csr_decode ;
  assign RDY_mv_csr_decode = 1'd1 ;

  // value method mv_csr_misa_c
  assign mv_csr_misa_c = csr_mv_csr_misa_c ;
  assign RDY_mv_csr_misa_c = 1'd1 ;

  // action method clint_msip
  assign RDY_clint_msip = 1'd1 ;
  assign CAN_FIRE_clint_msip = 1'd1 ;
  assign WILL_FIRE_clint_msip = EN_clint_msip ;

  // action method clint_mtip
  assign RDY_clint_mtip = 1'd1 ;
  assign CAN_FIRE_clint_mtip = 1'd1 ;
  assign WILL_FIRE_clint_mtip = EN_clint_mtip ;

  // action method clint_mtime
  assign RDY_clint_mtime = 1'd1 ;
  assign CAN_FIRE_clint_mtime = 1'd1 ;
  assign WILL_FIRE_clint_mtime = EN_clint_mtime ;

  // action method ext_interrupt
  assign RDY_ext_interrupt = 1'd1 ;
  assign CAN_FIRE_ext_interrupt = 1'd1 ;
  assign WILL_FIRE_ext_interrupt = EN_ext_interrupt ;

  // value method csr_updated
  assign csr_updated = 1'b0 ;
  assign RDY_csr_updated = 1'd1 ;

  // value method mv_interrupt
  assign mv_interrupt = csr_mv_interrupt ;

  // actionvalue method dump_get
  assign dump_get = dump_ff_D_OUT ;
  assign RDY_dump_get = dump_ff_EMPTY_N ;
  assign CAN_FIRE_dump_get = dump_ff_EMPTY_N ;
  assign WILL_FIRE_dump_get = EN_dump_get ;

  // value method mv_trigger_data1
  assign mv_trigger_data1 = csr_mv_trigger_data1 ;
  assign RDY_mv_trigger_data1 = 1'd1 ;

  // value method mv_trigger_data2
  assign mv_trigger_data2 = csr_mv_trigger_data2 ;
  assign RDY_mv_trigger_data2 = 1'd1 ;

  // value method mv_trigger_enable
  assign mv_trigger_enable = csr_mv_trigger_enable ;
  assign RDY_mv_trigger_enable = 1'd1 ;

  // value method mv_curr_priv
  assign mv_curr_priv = csr_mv_curr_priv ;
  assign RDY_mv_curr_priv = 1'd1 ;

  // action method ma_delayed_output
  assign RDY_ma_delayed_output = 1'd1 ;
  assign CAN_FIRE_ma_delayed_output = 1'd1 ;
  assign WILL_FIRE_ma_delayed_output = EN_ma_delayed_output ;

  // action method ma_events
  assign RDY_ma_events = 1'd1 ;
  assign CAN_FIRE_ma_events = 1'd1 ;
  assign WILL_FIRE_ma_events = EN_ma_events ;

  // value method mv_event_exceptions
  assign mv_event_exceptions = wr_event_exceptions_whas && x_wget__h1930 ;
  assign RDY_mv_event_exceptions = 1'd1 ;

  // value method mv_event_interrupts
  assign mv_event_interrupts =
	     wr_event_exceptions_whas &&
	     rx_stage3_type_first_x_BITS_37_TO_32__q1[5] ;
  assign RDY_mv_event_interrupts = 1'd1 ;

  // value method counter_values_fst
  assign counter_values_fst = csr_counter_values_fst ;
  assign RDY_counter_values_fst = 1'd1 ;

  // value method counter_values_snd
  assign counter_values_snd = csr_counter_values_snd ;
  assign RDY_counter_values_snd = 1'd1 ;

  // value method mv_pmp_cfg
  assign mv_pmp_cfg = csr_mv_pmp_cfg ;
  assign RDY_mv_pmp_cfg = 1'd1 ;

  // value method mv_pmp_addr
  assign mv_pmp_addr = csr_mv_pmp_addr ;
  assign RDY_mv_pmp_addr = 1'd1 ;

  // submodule csr
  mkcsr csr(.CLK(CLK),
	    .RST_N(RST_N),
	    .clint_msip_intrpt(csr_clint_msip_intrpt),
	    .clint_mtime_c_mtime(csr_clint_mtime_c_mtime),
	    .clint_mtip_intrpt(csr_clint_mtip_intrpt),
	    .ext_interrupt_ex_i(csr_ext_interrupt_ex_i),
	    .ma_events_e(csr_ma_events_e),
	    .system_instruction_csr_address(csr_system_instruction_csr_address),
	    .system_instruction_funct3(csr_system_instruction_funct3),
	    .system_instruction_lpc(csr_system_instruction_lpc),
	    .system_instruction_op1(csr_system_instruction_op1),
	    .take_trap_badaddr(csr_take_trap_badaddr),
	    .take_trap_pc(csr_take_trap_pc),
	    .take_trap_type_cause(csr_take_trap_type_cause),
	    .EN_system_instruction(csr_EN_system_instruction),
	    .EN_take_trap(csr_EN_take_trap),
	    .EN_clint_msip(csr_EN_clint_msip),
	    .EN_clint_mtip(csr_EN_clint_mtip),
	    .EN_clint_mtime(csr_EN_clint_mtime),
	    .EN_incr_minstret(csr_EN_incr_minstret),
	    .EN_ext_interrupt(csr_EN_ext_interrupt),
	    .EN_ma_events(csr_EN_ma_events),
	    .system_instruction(csr_system_instruction),
	    .RDY_system_instruction(),
	    .mv_csr_decode(csr_mv_csr_decode),
	    .RDY_mv_csr_decode(),
	    .take_trap(csr_take_trap),
	    .RDY_take_trap(),
	    .RDY_clint_msip(),
	    .RDY_clint_mtip(),
	    .RDY_clint_mtime(),
	    .RDY_incr_minstret(),
	    .RDY_ext_interrupt(),
	    .mv_csr_misa_c(csr_mv_csr_misa_c),
	    .RDY_mv_csr_misa_c(),
	    .mv_interrupt(csr_mv_interrupt),
	    .mv_curr_priv(csr_mv_curr_priv),
	    .RDY_mv_curr_priv(),
	    .csr_mstatus(),
	    .RDY_csr_mstatus(),
	    .mv_pmp_cfg(csr_mv_pmp_cfg),
	    .RDY_mv_pmp_cfg(),
	    .mv_pmp_addr(csr_mv_pmp_addr),
	    .RDY_mv_pmp_addr(),
	    .mv_trigger_data1(csr_mv_trigger_data1),
	    .RDY_mv_trigger_data1(),
	    .mv_trigger_data2(csr_mv_trigger_data2),
	    .RDY_mv_trigger_data2(),
	    .mv_trigger_enable(csr_mv_trigger_enable),
	    .RDY_mv_trigger_enable(),
	    .RDY_ma_events(),
	    .counter_values_fst(csr_counter_values_fst),
	    .RDY_counter_values_fst(),
	    .counter_values_snd(csr_counter_values_snd),
	    .RDY_counter_values_snd());

  // submodule dump_ff
  FIFOL1 #(.width(32'd103)) dump_ff(.RST(RST_N),
				    .CLK(CLK),
				    .D_IN(dump_ff_D_IN),
				    .ENQ(dump_ff_ENQ),
				    .DEQ(dump_ff_DEQ),
				    .CLR(dump_ff_CLR),
				    .D_OUT(dump_ff_D_OUT),
				    .FULL_N(dump_ff_FULL_N),
				    .EMPTY_N(dump_ff_EMPTY_N));

  // rule RL_instruction_commit
  assign CAN_FIRE_RL_instruction_commit =
	     rx_stage3_common_first_deq_rdy_b &&
	     rx_stage3_type_first_deq_rdy_b &&
	     rx_stage3_dump_first_deq_rdy_b &&
	     EN_ma_delayed_output &&
	     dump_ff_FULL_N ;
  assign WILL_FIRE_RL_instruction_commit = CAN_FIRE_RL_instruction_commit ;

  // rule RL_increment_instruction_counter
  assign CAN_FIRE_RL_increment_instruction_counter = RDY_commit_rd_get ;
  assign WILL_FIRE_RL_increment_instruction_counter =
	     CAN_FIRE_RL_increment_instruction_counter &&
	     !WILL_FIRE_RL_instruction_commit ;

  // rule RL_wr_memory_response__dreg_update
  assign CAN_FIRE_RL_wr_memory_response__dreg_update = 1'd1 ;
  assign WILL_FIRE_RL_wr_memory_response__dreg_update = 1'd1 ;

  // inlined wires
  assign ff_stage3_common_w_ena_whas =
	     WILL_FIRE_RL_instruction_commit &&
	     (rg_rerun_18_OR_ff_stage3_type_w_data_whas__6_A_ETC___d123 ||
	      _dfoo17) ;
  assign ff_stage3_type_w_ena_whas =
	     WILL_FIRE_RL_instruction_commit &&
	     (rg_rerun_18_OR_ff_stage3_type_w_data_whas__6_A_ETC___d123 ||
	      _dfoo17) ;
  assign ff_stage3_dump_w_ena_whas =
	     WILL_FIRE_RL_instruction_commit &&
	     (rg_rerun_18_OR_ff_stage3_type_w_data_whas__6_A_ETC___d123 ||
	      _dfoo17) ;
  assign wr_memory_response_1_wget = { 1'd1, memory_response_put } ;
  assign wr_operand_fwding_wget =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d160 ?
	       { rx_stage3_common_first_x[5:1],
		 data__h4022,
		 !rx_stage3_type_first_x[0] || ma_delayed_output_r[0] } :
	       { rx_stage3_common_first_x[5:1], _theResult____h5217, 1'd1 } ;
  assign wr_operand_fwding_whas = WILL_FIRE_RL_instruction_commit && _dfoo25 ;
  assign wr_commit_wget =
	     (rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	      NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d175) ?
	       { 1'd1, rx_stage3_common_first_x[5:1], data__h4022 } :
	       _dfoo10 ;
  assign wr_commit_whas = WILL_FIRE_RL_instruction_commit && _dfoo15 ;
  assign wr_flush_wget =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d124 ?
	       { rg_rerun ? rx_stage3_common_first_x[37:6] : csr_take_trap,
		 1'd1 } :
	       _dfoo14 ;
  assign wr_flush_whas =
	     WILL_FIRE_RL_instruction_commit &&
	     (rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d124 ||
	      _dfoo11) ;
  assign wr_event_exceptions_whas =
	     WILL_FIRE_RL_instruction_commit &&
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d147 ;

  // register rg_epoch
  assign rg_epoch_D_IN = x__h5568 ;
  assign rg_epoch_EN =
	     WILL_FIRE_RL_instruction_commit &&
	     (rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d124 ||
	      _dfoo11) ;

  // register rg_rerun
  assign rg_rerun_D_IN =
	     !rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 ||
	     !rg_rerun_18_OR_ff_stage3_type_w_data_whas__6_A_ETC___d134 ||
	     !rg_rerun ;
  assign rg_rerun_EN =
	     WILL_FIRE_RL_instruction_commit &&
	     (rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	      rg_rerun_18_OR_ff_stage3_type_w_data_whas__6_A_ETC___d134 ||
	      rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	      !rg_rerun &&
	      rx_stage3_type_first_x[50:49] == 2'd0 &&
	      rx_stage3_type_first_x[35:34] == 2'd3) ;

  // register wr_memory_response
  assign wr_memory_response_D_IN =
	     EN_memory_response_put ?
	       wr_memory_response_1_wget :
	       { 1'd0, 34'h2AAAAAAAA /* unspecified value */  } ;
  assign wr_memory_response_EN = 1'd1 ;

  // submodule csr
  assign csr_clint_msip_intrpt = clint_msip_intrpt ;
  assign csr_clint_mtime_c_mtime = clint_mtime_c_mtime ;
  assign csr_clint_mtip_intrpt = clint_mtip_intrpt ;
  assign csr_ext_interrupt_ex_i = ext_interrupt_i ;
  assign csr_ma_events_e = ma_events_e ;
  assign csr_system_instruction_csr_address = rx_stage3_type_first_x[14:3] ;
  assign csr_system_instruction_funct3 = rx_stage3_type_first_x[2:0] ;
  assign csr_system_instruction_lpc = rx_stage3_type_first_x[16:15] ;
  assign csr_system_instruction_op1 = rx_stage3_type_first_x[48:17] ;
  assign csr_take_trap_badaddr =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d147 ?
	       rx_stage3_type_first_x[31:0] :
	       wr_memory_response[33:2] ;
  assign csr_take_trap_pc = rx_stage3_common_first_x[37:6] ;
  assign csr_take_trap_type_cause =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d147 ?
	       rx_stage3_type_first_x[37:32] :
	       type_cause__h5287 ;
  assign csr_EN_system_instruction =
	     WILL_FIRE_RL_instruction_commit &&
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d196 ;
  assign csr_EN_take_trap =
	     WILL_FIRE_RL_instruction_commit &&
	     (rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d147 ||
	      rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	      !rg_rerun &&
	      ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d239) ;
  assign csr_EN_clint_msip = EN_clint_msip ;
  assign csr_EN_clint_mtip = EN_clint_mtip ;
  assign csr_EN_clint_mtime = EN_clint_mtime ;
  assign csr_EN_incr_minstret = WILL_FIRE_RL_increment_instruction_counter ;
  assign csr_EN_ext_interrupt = EN_ext_interrupt ;
  assign csr_EN_ma_events = EN_ma_events ;

  // submodule dump_ff
  assign dump_ff_D_IN =
	     (rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	      NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d175) ?
	       { csr_mv_curr_priv,
		 rx_stage3_dump_first_x,
		 rx_stage3_common_first_x[5:1],
		 data__h4022 } :
	       _dfoo2 ;
  assign dump_ff_ENQ = WILL_FIRE_RL_instruction_commit && _dfoo15 ;
  assign dump_ff_DEQ = EN_dump_get ;
  assign dump_ff_CLR = 1'b0 ;

  // remaining internal signals
  assign NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d175 =
	     !rg_rerun && rx_stage3_type_first_x[50:49] == 2'd2 &&
	     (!rx_stage3_type_first_x[0] || ma_delayed_output_r[0]) ;
  assign NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d183 =
	     !rg_rerun && rx_stage3_type_first_x[50:49] == 2'd2 &&
	     rx_stage3_type_first_x[0] &&
	     !ma_delayed_output_r[0] ;
  assign NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d198 =
	     !rg_rerun && rx_stage3_type_first_x[50:49] == 2'd3 &&
	     csr_system_instruction[64] ;
  assign _dfoo10 =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d196 ?
	       { 1'd1, rx_stage3_common_first_x[5:1], _theResult____h4904 } :
	       ((rx_stage3_type_first_x[35:34] == 2'd3) ?
		  38'h2000000000 :
		  { 1'd1,
		    rx_stage3_common_first_x[5:1],
		    _theResult____h5217 }) ;
  assign _dfoo11 =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	     (NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d198 ||
	      !rg_rerun &&
	      ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d239) ;
  assign _dfoo14 =
	     (rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	      NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d198) ?
	       { csr_system_instruction[63:32], 1'd1 } :
	       { csr_take_trap, 1'd1 } ;
  assign _dfoo15 =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	     NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d175 ||
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d196 ||
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	     !rg_rerun &&
	     rx_stage3_type_first_x[50:49] == 2'd0 &&
	     (rx_stage3_type_first_x[35:34] == 2'd3 ||
	      wr_memory_response[34] &&
	      wr_memory_response_10_BIT_0_12_EQ_rg_epoch_20___d213 &&
	      !wr_memory_response[1]) ;
  assign _dfoo17 =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	     NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d175 ||
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d196 ||
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	     !rg_rerun &&
	     rx_stage3_type_first_x[50:49] == 2'd0 &&
	     (rx_stage3_type_first_x[35:34] == 2'd3 ||
	      wr_memory_response[34] &&
	      wr_memory_response_10_BIT_0_12_EQ_rg_epoch_20___d213) ;
  assign _dfoo2 =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d196 ?
	       { csr_mv_curr_priv,
		 rx_stage3_dump_first_x,
		 rx_stage3_common_first_x[5:1],
		 _theResult____h4904 } :
	       csr_mv_curr_priv__79_CONCAT_ff_stage3_dump_w_d_ETC___d232 ;
  assign _dfoo25 =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d160 ||
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	     !rg_rerun &&
	     rx_stage3_type_first_x[50:49] == 2'd0 &&
	     rx_stage3_type_first_x[35:34] != 2'd3 &&
	     wr_memory_response[34] &&
	     wr_memory_response_10_BIT_0_12_EQ_rg_epoch_20___d213 &&
	     !wr_memory_response[1] ;
  assign _theResult_____1_fst__h4142 =
	     (!ma_delayed_output_r[0] ||
	      rx_stage3_common_first_x[5:1] == 5'd0) ?
	       _theResult____h4019 :
	       ma_delayed_output_r[32:1] ;
  assign _theResult____h4019 =
	     (rx_stage3_common_first_x[5:1] == 5'd0) ?
	       32'd0 :
	       rx_stage3_type_first_x[32:1] ;
  assign _theResult____h4904 =
	     (rx_stage3_common_first_x[5:1] == 5'd0) ?
	       32'd0 :
	       csr_system_instruction[31:0] ;
  assign _theResult____h5217 =
	     (rx_stage3_common_first_x[5:1] == 5'd0) ?
	       32'd0 :
	       wr_memory_response[33:2] ;
  assign csr_mv_curr_priv__79_CONCAT_ff_stage3_dump_w_d_ETC___d232 =
	     { csr_mv_curr_priv,
	       rx_stage3_dump_first_x,
	       (rx_stage3_type_first_x[35:34] == 2'd3) ?
		 37'd0 :
		 { rx_stage3_common_first_x[5:1], _theResult____h5217 } } ;
  assign data__h4022 =
	     rx_stage3_type_first_x[0] ?
	       _theResult_____1_fst__h4142 :
	       _theResult____h4019 ;
  assign ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d239 =
	     rx_stage3_type_first_x[50:49] == 2'd0 &&
	     rx_stage3_type_first_x[35:34] != 2'd3 &&
	     wr_memory_response[34] &&
	     wr_memory_response_10_BIT_0_12_EQ_rg_epoch_20___d213 &&
	     wr_memory_response[1] ;
  assign ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d266 =
	     rx_stage3_type_first_x[50:49] == 2'd0 &&
	     rx_stage3_type_first_x[35:34] != 2'd3 &&
	     (!wr_memory_response[34] ||
	      !wr_memory_response_10_BIT_0_12_EQ_rg_epoch_20___d213) ;
  assign rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 =
	     rg_epoch == rx_stage3_common_first_x[0] ;
  assign rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d124 =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	     (rg_rerun || rx_stage3_type_first_x[50:49] == 2'd1) ;
  assign rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d147 =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	     !rg_rerun &&
	     rx_stage3_type_first_x[50:49] == 2'd1 ;
  assign rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d160 =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	     !rg_rerun &&
	     rx_stage3_type_first_x[50:49] == 2'd2 ;
  assign rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d196 =
	     rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	     !rg_rerun &&
	     rx_stage3_type_first_x[50:49] == 2'd3 ;
  assign rg_rerun_18_OR_ff_stage3_type_w_data_whas__6_A_ETC___d123 =
	     rg_rerun || rx_stage3_type_first_x[50:49] == 2'd1 ||
	     !rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 ;
  assign rg_rerun_18_OR_ff_stage3_type_w_data_whas__6_A_ETC___d134 =
	     rg_rerun ||
	     rx_stage3_type_first_x[50:49] == 2'd3 &&
	     !csr_system_instruction[64] ;
  assign rx_stage3_type_first_x_BITS_37_TO_32__q1 =
	     rx_stage3_type_first_x[37:32] ;
  assign type_cause__h5287 =
	     (rx_stage3_type_first_x[35:34] == 2'd0) ? 6'd5 : 6'd7 ;
  assign wr_memory_response_10_BIT_0_12_EQ_rg_epoch_20___d213 =
	     wr_memory_response[0] == rg_epoch ;
  assign x__h5568 = ~rg_epoch ;
  assign x__read_rdaddr__h6673 =
	     wr_operand_fwding_whas ? wr_operand_fwding_wget[37:33] : 5'd0 ;
  assign x__read_rdvalue__h6674 =
	     wr_operand_fwding_whas ? wr_operand_fwding_wget[32:1] : 32'd0 ;
  assign x_wget__h1930 = ~rx_stage3_type_first_x_BITS_37_TO_32__q1[5] ;

  // handling of inlined registers

  always@(posedge CLK or `BSV_RESET_EDGE RST_N)
  if (RST_N == `BSV_RESET_VALUE)
    begin
      rg_epoch <= `BSV_ASSIGNMENT_DELAY 1'd0;
      rg_rerun <= `BSV_ASSIGNMENT_DELAY 1'd0;
      wr_memory_response <= `BSV_ASSIGNMENT_DELAY
	  { 1'd0, 34'h2AAAAAAAA /* unspecified value */  };
    end
  else
    begin
      if (rg_epoch_EN) rg_epoch <= `BSV_ASSIGNMENT_DELAY rg_epoch_D_IN;
      if (rg_rerun_EN) rg_rerun <= `BSV_ASSIGNMENT_DELAY rg_rerun_D_IN;
      if (wr_memory_response_EN)
	wr_memory_response <= `BSV_ASSIGNMENT_DELAY wr_memory_response_D_IN;
    end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rg_epoch = 1'h0;
    rg_rerun = 1'h0;
    wr_memory_response = 35'h2AAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  TASK_testplusargs___d14 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  TASK_testplusargs___d15 = $test$plusargs("mstage3");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  TASK_testplusargs___d16 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  v__h2104 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("[%10d", v__h2104, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("STAGE3: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("TraceDump { ", "pc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("'h%h", rx_stage3_dump_first_x[63:32]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write(", ", "instruction: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("'h%h", rx_stage3_dump_first_x[31:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d14 ||
	   TASK_testplusargs___d15 && TASK_testplusargs___d16))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  TASK_testplusargs___d26 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  TASK_testplusargs___d27 = $test$plusargs("mstage3");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  TASK_testplusargs___d28 = $test$plusargs("l0");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  v__h2314 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d26 ||
	   TASK_testplusargs___d27 && TASK_testplusargs___d28))
	$write("[%10d", v__h2314, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d26 ||
	   TASK_testplusargs___d27 && TASK_testplusargs___d28))
	$write("STAGE3: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d26 ||
	   TASK_testplusargs___d27 && TASK_testplusargs___d28))
	$write("Stage3Common { ", "pc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d26 ||
	   TASK_testplusargs___d27 && TASK_testplusargs___d28))
	$write("'h%h", rx_stage3_common_first_x[37:6]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d26 ||
	   TASK_testplusargs___d27 && TASK_testplusargs___d28))
	$write(", ", "rd: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d26 ||
	   TASK_testplusargs___d27 && TASK_testplusargs___d28))
	$write("'h%h", rx_stage3_common_first_x[5:1]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d26 ||
	   TASK_testplusargs___d27 && TASK_testplusargs___d28))
	$write(", ", "epoch: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d26 ||
	   TASK_testplusargs___d27 && TASK_testplusargs___d28))
	$write("'h%h", rx_stage3_common_first_x[0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d26 ||
	   TASK_testplusargs___d27 && TASK_testplusargs___d28))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  TASK_testplusargs___d40 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  TASK_testplusargs___d41 = $test$plusargs("mstage3");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  TASK_testplusargs___d42 = $test$plusargs("l0");
	  #0;
	end
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] == 2'd0;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] == 2'd1;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] == 2'd2;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] != 2'd0 &&
	rx_stage3_type_first_x[50:49] != 2'd1 &&
	rx_stage3_type_first_x[50:49] != 2'd2;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d86 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] == 2'd2 &&
	rx_stage3_type_first_x[0];
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d89 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] == 2'd2 &&
	!rx_stage3_type_first_x[0];
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d91 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] != 2'd0 &&
	rx_stage3_type_first_x[50:49] != 2'd1;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d98 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] != 2'd0;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d102 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] == 2'd0 &&
	rx_stage3_type_first_x[35:34] == 2'd0;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d105 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] == 2'd0 &&
	rx_stage3_type_first_x[35:34] == 2'd1;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d108 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] == 2'd0 &&
	rx_stage3_type_first_x[35:34] == 2'd3;
    TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d115 =
	(TASK_testplusargs___d40 ||
	 TASK_testplusargs___d41 && TASK_testplusargs___d42) &&
	rx_stage3_type_first_x[50:49] == 2'd0 &&
	rx_stage3_type_first_x[35:34] != 2'd0 &&
	rx_stage3_type_first_x[35:34] != 2'd1 &&
	rx_stage3_type_first_x[35:34] != 2'd3;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit)
	begin
	  v__h2544 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d40 ||
	   TASK_testplusargs___d41 && TASK_testplusargs___d42))
	$write("[%10d", v__h2544, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d40 ||
	   TASK_testplusargs___d41 && TASK_testplusargs___d42))
	$write("STAGE3: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("tagged Memory ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("tagged Trap ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("tagged Regular ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write("tagged System ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write("Stage3System { ", "rs1_imm: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write("'h%h", rx_stage3_type_first_x[48:17]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write(", ", "lpc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write("'h%h", rx_stage3_type_first_x[16:15]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write(", ", "csr_address: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write("'h%h", rx_stage3_type_first_x[14:3]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write(", ", "funct3: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write("'h%h", rx_stage3_type_first_x[2:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("Stage3Regular { ", "rdvalue: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write("'h%h", rx_stage3_type_first_x[32:1]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write(", ", "delayed: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d86)
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d89)
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d57)
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d67)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("Stage3Trap { ", "cause: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d91)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("'h%h", rx_stage3_type_first_x[37:32]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d91)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write(", ", "badaddr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d91)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d54)
	$write("'h%h", rx_stage3_type_first_x[31:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d91)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("Stage3Memory { ", "memaccess: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d98)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d102)
	$write("Load");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d105)
	$write("Store");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d108)
	$write("Fence");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d115)
	$write("Atomic");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d98)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write(", ", "address: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d98)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("'h%h", rx_stage3_type_first_x[33:2]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d98)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write(", ", "size: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d98)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d51)
	$write("'h%h", rx_stage3_type_first_x[1:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  TASK_testplusargs_0_OR_TASK_testplusargs_1_AND_ETC___d98)
	$write("");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  (TASK_testplusargs___d40 ||
	   TASK_testplusargs___d41 && TASK_testplusargs___d42))
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  rg_rerun)
	begin
	  TASK_testplusargs___d138 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  rg_rerun)
	begin
	  TASK_testplusargs___d139 = $test$plusargs("mstage3");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  rg_rerun)
	begin
	  TASK_testplusargs___d140 = $test$plusargs("l0");
	  #0;
	end
    rg_rerun_18_AND_TASK_testplusargs_38_OR_TASK_t_ETC___d143 =
	rg_rerun &&
	(TASK_testplusargs___d138 ||
	 TASK_testplusargs___d139 && TASK_testplusargs___d140);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  rg_rerun)
	begin
	  v__h3959 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  rg_rerun_18_AND_TASK_testplusargs_38_OR_TASK_t_ETC___d143)
	$write("[%10d", v__h3959, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  rg_rerun_18_AND_TASK_testplusargs_38_OR_TASK_t_ETC___d143)
	$write("STAGE3: Rerun Instruction");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  rg_rerun_18_AND_TASK_testplusargs_38_OR_TASK_t_ETC___d143)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d147)
	begin
	  TASK_testplusargs___d148 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d147)
	begin
	  TASK_testplusargs___d149 = $test$plusargs("mstage3");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d147)
	begin
	  TASK_testplusargs___d150 = $test$plusargs("l0");
	  #0;
	end
    ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d153 =
	rx_stage3_type_first_x[50:49] == 2'd1 &&
	(TASK_testplusargs___d148 ||
	 TASK_testplusargs___d149 && TASK_testplusargs___d150);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d147)
	begin
	  v__h3622 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  !rg_rerun &&
	  ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d153)
	$write("[%10d", v__h3622, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  !rg_rerun &&
	  ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d153)
	$write("STAGE3 : Jumping to PC:%h", csr_take_trap);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  !rg_rerun &&
	  ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d153)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d183)
	begin
	  TASK_testplusargs___d185 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d183)
	begin
	  TASK_testplusargs___d186 = $test$plusargs("mstage3");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d183)
	begin
	  TASK_testplusargs___d187 = $test$plusargs("l0");
	  #0;
	end
    ff_stage3_type_w_data_wget__7_BIT_0_4_AND_NOT__ETC___d190 =
	rx_stage3_type_first_x[0] && !ma_delayed_output_r[0] &&
	(TASK_testplusargs___d185 ||
	 TASK_testplusargs___d186 && TASK_testplusargs___d187);
    NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d192 =
	!rg_rerun && rx_stage3_type_first_x[50:49] == 2'd2 &&
	ff_stage3_type_w_data_wget__7_BIT_0_4_AND_NOT__ETC___d190;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d183)
	begin
	  v__h4447 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d192)
	$write("[%10d", v__h4447, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d192)
	$write("STAGE3: Waiting for Delayed Output");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d192)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  !rg_rerun &&
	  ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d239)
	begin
	  TASK_testplusargs___d245 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  !rg_rerun &&
	  ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d239)
	begin
	  TASK_testplusargs___d246 = $test$plusargs("mstage3");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  !rg_rerun &&
	  ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d239)
	begin
	  TASK_testplusargs___d247 = $test$plusargs("l0");
	  #0;
	end
    wr_memory_response_10_BIT_1_15_AND_TASK_testpl_ETC___d250 =
	wr_memory_response[1] &&
	(TASK_testplusargs___d245 ||
	 TASK_testplusargs___d246 && TASK_testplusargs___d247);
    NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d254 =
	!rg_rerun && rx_stage3_type_first_x[50:49] == 2'd0 &&
	rx_stage3_type_first_x[35:34] != 2'd3 &&
	wr_memory_response[34] &&
	wr_memory_response_10_BIT_0_12_EQ_rg_epoch_20___d213 &&
	wr_memory_response_10_BIT_1_15_AND_TASK_testpl_ETC___d250;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  !rg_rerun &&
	  ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d239)
	begin
	  v__h5691 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d254)
	$write("[%10d", v__h5691, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d254)
	$write("STAGE3 : Jumping to PC:%h", csr_take_trap);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d254)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  !rg_rerun &&
	  ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d266)
	begin
	  TASK_testplusargs___d269 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  !rg_rerun &&
	  ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d266)
	begin
	  TASK_testplusargs___d270 = $test$plusargs("mstage3");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  !rg_rerun &&
	  ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d266)
	begin
	  TASK_testplusargs___d271 = $test$plusargs("l1");
	  #0;
	end
    NOT_wr_memory_response_10_BIT_34_11_62_OR_NOT__ETC___d274 =
	(!wr_memory_response[34] ||
	 !wr_memory_response_10_BIT_0_12_EQ_rg_epoch_20___d213) &&
	(TASK_testplusargs___d269 ||
	 TASK_testplusargs___d270 && TASK_testplusargs___d271);
    NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d277 =
	!rg_rerun && rx_stage3_type_first_x[50:49] == 2'd0 &&
	rx_stage3_type_first_x[35:34] != 2'd3 &&
	NOT_wr_memory_response_10_BIT_34_11_62_OR_NOT__ETC___d274;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  !rg_rerun &&
	  ff_stage3_type_w_data_whas__6_AND_ff_stage3_ty_ETC___d266)
	begin
	  v__h5765 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d277)
	$write("[%10d", v__h5765, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d277)
	$write("STAGE3 : Waiting for response from Fabric");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	  NOT_rg_rerun_18_36_AND_ff_stage3_type_w_data_w_ETC___d277)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  !rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121)
	begin
	  TASK_testplusargs___d280 = $test$plusargs("fullverbose");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  !rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121)
	begin
	  TASK_testplusargs___d281 = $test$plusargs("mstage3");
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  !rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121)
	begin
	  TASK_testplusargs___d282 = $test$plusargs("l0");
	  #0;
	end
    NOT_rg_epoch_20_EQ_IF_ff_stage3_common_w_data__ETC___d285 =
	!rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121 &&
	(TASK_testplusargs___d280 ||
	 TASK_testplusargs___d281 && TASK_testplusargs___d282);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  !rg_epoch_20_EQ_IF_ff_stage3_common_w_data_whas_ETC___d121)
	begin
	  v__h5860 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  NOT_rg_epoch_20_EQ_IF_ff_stage3_common_w_data__ETC___d285)
	$write("[%10d", v__h5860, "] ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  NOT_rg_epoch_20_EQ_IF_ff_stage3_common_w_data__ETC___d285)
	$write("STAGE3 : Dropping instruction");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_instruction_commit &&
	  NOT_rg_epoch_20_EQ_IF_ff_stage3_common_w_data__ETC___d285)
	$write("\n");
  end
  // synopsys translate_on
endmodule  // mkstage3

