//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Mar 31 00:26:12 IST 2025
//
//
// Ports:
// Name                         I/O  size props
// singlestep                     O    65
// singlestep_remainder           I    33
// singlestep_quotient            I    32
// singlestep_divisor             I    32
//
// Combinational paths from inputs to outputs:
//   (singlestep_remainder,
//    singlestep_quotient,
//    singlestep_divisor) -> singlestep
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_singlestep(singlestep_remainder,
			 singlestep_quotient,
			 singlestep_divisor,
			 singlestep);
  // value method singlestep
  input  [32 : 0] singlestep_remainder;
  input  [31 : 0] singlestep_quotient;
  input  [31 : 0] singlestep_divisor;
  output [64 : 0] singlestep;

  // signals for module outputs
  wire [64 : 0] singlestep;

  // remaining internal signals
  wire [32 : 0] remainder__h62, sub__h64, x__h24;
  wire [31 : 0] x__h101, x__h96;
  wire singlestep_remainder_BITS_30_TO_0_CONCAT_singl_ETC___d4;

  // value method singlestep
  assign singlestep = { x__h24, x__h101 } ;

  // remaining internal signals
  assign remainder__h62 =
	     { singlestep_remainder[31:0], singlestep_quotient[31] } ;
  assign singlestep_remainder_BITS_30_TO_0_CONCAT_singl_ETC___d4 =
	     { singlestep_remainder[30:0], singlestep_quotient[31] } <
	     singlestep_divisor ;
  assign sub__h64 = remainder__h62 + { x__h96[31], x__h96 } ;
  assign x__h101 =
	     { singlestep_quotient[30:0],
	       !singlestep_remainder_BITS_30_TO_0_CONCAT_singl_ETC___d4 } ;
  assign x__h24 =
	     singlestep_remainder_BITS_30_TO_0_CONCAT_singl_ETC___d4 ?
	       remainder__h62 :
	       sub__h64 ;
  assign x__h96 = ~singlestep_divisor + 32'd1 ;
endmodule  // module_singlestep

